#!/usr/bin/env sh
set -e

echo "Build hook running"

TAG=$1
TAG=${TAG:=latest}

export COMMIT_HASH=`git rev-parse --short HEAD`

export IMAGE_COMMIT=zaherg/php72-swoole:$TAG-$COMMIT_HASH

export IMAGE_NAME=zaherg/php72-swoole:$TAG && \
             docker build --no-cache --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --file Dockerfile \
             --build-arg VCS_REF=$COMMIT_HASH \
             --build-arg IMAGE_NAME=$IMAGE_NAME \
             --squash --force-rm --compress --rm \
             -t $IMAGE_NAME .
